---
title: "蜂群柱状图示例"
Author: "Binjie Yang"
date: "2024.03.19"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}

suppressMessages(library("tidyverse")) # to organize data
suppressMessages(library("emmeans"))  # emmeans is needed for follow-up tests 
suppressMessages(library("ggplot2")) # for plotting
suppressMessages(library("ggsci")) # for setting scientific journal color palettes 
suppressMessages(library("gridExtra")) # for arranging the position of figures
suppressMessages(library("ggpubr")) # using the ggexport
suppressMessages(library("ggthemes"))#provide theme for plot
suppressMessages(library("patchwork")) 

library(ggnewscale)
library(ggpubr)
library(ggsignif)
library(ggnewscale)
library(ggbeeswarm)
library(ggsignif)
library(magrittr)

select <- dplyr::select # to avoid clashes with the MASS package

```


```{r loaddata}

raw_data  <- read.csv(file="bias_data.csv",head=TRUE)
#note: one subject's data deleted because of the eye-tracking hdf5 file was missing

data_df <- raw_data

```


```{r data cleaning}

data_df          <- data_df %>% filter(consistency != 'filler')

#将变量转换为因子型
data_df$subid          <- factor(data_df$subid)
data_df$type           <- factor(data_df$type)
data_df$consistency    <- factor(data_df$consistency)

data_df$consistency2   <- factor(data_df$consistency,levels=c('c','i1','i2')) #reorder the levels; consistency2 was computed to avoid errors in emmeans package.

#我们的因变量为多项分布的数据，这里也把它因子化
data_df$bias <- factor(data_df$bias, ordered = TRUE)

```


```{r mean data of paticipant}

data_df$bias        <- as.character(data_df$bias)
data_df$bias        <- as.numeric(data_df$bias)

description0_df     <- data_df %>% group_by(type) %>%
  summarise(des_bias = mean(bias), des_sd = sd(bias))

description1_df     <- data_df %>% group_by(consistency) %>%
  summarise(des_bias = mean(bias), des_sd = sd(bias))

description2_df     <- data_df %>% group_by(type, consistency) %>%
  summarise(des_bias = mean(bias), des_sd = sd(bias))

mean_df             <- data_df %>% group_by(subid, type, consistency) %>%
  summarise(mean_bias = mean(bias))

mean_df$consistency <- ifelse(mean_df$consistency == "c", "consistent", 
                              ifelse(mean_df$consistency == "i1",
                                     "inconsistent1",
                                    "inconsistent2"))

print(description0_df)
print(description1_df)
print(description2_df)
print(mean_df)

```


```{r plot loading data}

mean_df$consistency <- factor(mean_df$consistency)  #将自变量转换为因子型
mean_df$type <- factor(mean_df$type, levels = c("person", "fan"))
#如果对于自变量的排序有要求，需要手动指定levels

```


```{r 前置工作/画背景}

#前置工作，设定各种基础参数
windowsFonts(N=windowsFont("Times New Roman"),A=windowsFont("Arial")) 

p<-ggplot(mean_df, aes(x = type, y = mean_bias, 
                       fill = consistency,color = consistency)) +
#设定x轴和y轴，同时设定图例，fill为填充，color为边框
  
  scale_y_continuous(limits = c(-1,1.2),
                     breaks = seq(from=-1 ,to=1, by=0.4),
                     expand = expansion(mult = c(0, 0.1))) +
  labs(x = "Type", y = "Fixation bias") +
#设定x轴和y轴的最小和最大值以及步长，expand函数用于在设定轴上创造额外的空间
  
  scale_colour_manual(values=c("#F3627B","#e5be79","#3e86b5"),name='consistency')+
  scale_fill_manual(values=c("#F3627B","#e5be79","#3e86b5"),name='consistency')+
#设定color和fill的颜色，此处为全局设定，但是后面可以用ggnewscale包进行局部设定
  
  theme(legend.position="right",
        legend.title = element_text(size=10,colour='black',family="A"),
        legend.text = element_text(size=10,colour='black',family="A"),
        legend.key.size=unit(0.5,"cm"),
        #图例的设定
        
        axis.ticks.length = unit(0.1, "cm"),  #轴上刻度长度的设定
        axis.text.x = element_text(size=16,colour='black',family ="A"),
        axis.text.y = element_text(size=16,colour='black',family="A"),
        axis.title.x = element_text(size=20,colour='black',family="A"),
        axis.title.y = element_text(size=20,colour='black',family="A"))
        #轴标题以及轴刻度文字的设定
p

```


```{r background}
p1<-p + geom_bar(position=position_dodge(),
                 stat="summary",colour = "black",size=0.5)
p1

p2 <- p1  + geom_vline(aes(xintercept=as.numeric(as.factor(type))+0.5),
                      linetype=2,cex=1.2)+
      geom_rect(aes(xmin=as.numeric(as.factor(type))+0.5,
                    xmax=Inf, ymin=(-Inf),ymax=Inf),
                fill='grey90',color='grey90')+
      geom_vline(xintercept =data_df$condictions,linetype=2,cex=1.2)+
      geom_bar(position=position_dodge(),
               stat="summary",colour = "black",size=0.5)
p2
```

                  
```{r error bar}

p3 <- p2 + geom_beeswarm(data = mean_df, aes(y = mean_bias),
                         dodge.width = 0.9,
                         shape = 21, size = 3, stroke = 0.5) +
      scale_colour_manual(values=c("black","black","black"),
                          name='consistency')+
      stat_summary(fun.data = 'mean_se', geom = "errorbar",
                   colour = "black",
                   width = 0.2,position = position_dodge(0.9))+
      geom_signif(y_position=c(0.9, 0.9),
                  xmin=c(0.85, 1.85),
                  xmax=c(1.15, 2.15),
                  annotation=c("***","***"), 
                  tip_length=0, size= NA, textsize = 7,  vjust = 0.4)+
      geom_signif(y_position=1.2,xmin=0.7,xmax=1.7,
                  annotation="**",
                  tip_length=0.05, size= 0.6, textsize = 7,  vjust = 0.4)

p3
#去掉灰底, 去掉背景网格线, 去掉顶部和右侧框线
p4 <- p3+theme_bw()+   #使用bw这个theme自动优化图形的美观性
  theme(panel.grid=element_blank()) +
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank())

p4
```


```{r save the plot}

ggsave(p4, filename = "exp2_bias.pdf", dpi = 500,
       width=2800,height=2000,units = "px")
#保存成pdf可以方便之后修改dpi信息(pdf储存的为矢量图)

```